src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $matricule = '';

    #[ORM\Column(length: 255)]
    private ?string $firstname = '';

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(length: 20)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $service = null;

    #[ORM\Column(length: 255)]
    private ?string $speciality = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    /**
     * @var Collection<int, Adress>
     */
    #[ORM\OneToMany(targetEntity: Adress::class, mappedBy: 'user')]
    private Collection $adresses;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\ManyToMany(targetEntity: Project::class, mappedBy: 'user')]
    private Collection $projects;

    /**
     * @var Collection<int, Taches>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Taches::class)]
    private Collection $taches;

    #[ORM\OneToMany(mappedBy: 'LeaderProject', targetEntity: Taches::class)]
    private Collection $leadProjectTaches;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $token = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $tokenExpiredAt = null;

    public function __toString(): string
    {
        return $this->email . ' ' . $this->lastname;  
    }
    

    
    public function __construct()
    {
        $this->adresses = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->taches = new ArrayCollection();
        $this->leadProjectTaches = new ArrayCollection();
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
{
    if (!in_array($role, $this->roles, true)) {
        $this->roles[] = $role;
    }
    return $this;
}

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(?string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(?string $service): static
    {
        $this->service = $service;

        return $this;
    }

    public function getSpeciality(): ?string
    {
        return $this->speciality;
    }

    public function setSpeciality(?string $speciality): static
    {
        $this->speciality = $speciality;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Adress>
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adress $adress): static
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses->add($adress);
            $adress->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adress $adress): static
    {
        if ($this->adresses->removeElement($adress)) {
            // set the owning side to null (unless already changed)
            if ($adress->getUser() === $this) {
                $adress->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->addUser($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            $project->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Taches>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTache(Taches $tache): static
    {
        if (!$this->taches->contains($tache)) {
            $this->taches->add($tache);
            $tache->setUser($this);
        }

        return $this;
    }

    public function removeTache(Taches $tache): static
    {
        if ($this->taches->removeElement($tache)) {
            
            if ($tache->getUser() === $this) {
                $tache->setUser(null);
            }
        }

        return $this;
    }
        public function getUsername(): ?string
    {
        return $this->email; 
    }

    public function getLeadProjectTaches(): Collection
    {
        return $this->leadProjectTaches;
    }

    public function addLeadProjectTache(Taches $tache): static
    {
        if (!$this->leadProjectTaches->contains($tache)) {
            $this->leadProjectTaches->add($tache);
            $tache->setLeaderProject($this);
        }

        return $this;
    }

    public function removeLeadProjectTache(Taches $tache): static
    {
        if ($this->leadProjectTaches->removeElement($tache)) {
            if ($tache->getLeaderProject() === $this) {
                $tache->setLeaderProject(null);
            }
        }

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getTokenExpiredAt(): ?\DateTimeInterface
    {
        return $this->tokenExpiredAt;
    }

    public function setTokenExpiredAt(?\DateTimeInterface $tokenExpiredAt): static
    {
        $this->tokenExpiredAt = $tokenExpiredAt;

        return $this;
    }
}


    

src/Controller/ChatController.php
<?php
// src/Controller/ChatController.php
namespace App\Controller;

use App\Entity\ChatMessage;
use App\Form\ChatMessageType;
use App\Repository\ChatMessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/chat')]
class ChatController extends AbstractController
{
    #[Route('/', name: 'app_chat', methods: ['GET', 'POST'])]
    public function index(Request $request, ChatMessageRepository $chatMessageRepository, EntityManagerInterface $entityManager): Response
    {
        $message = new ChatMessage();
        $form = $this->createForm(ChatMessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setUser($this->getUser());
            $message->setCreatedAt(new \DateTime());
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('app_chat');
        }

        $messages = $chatMessageRepository->findBy([], ['createdAt' => 'ASC']);

        return $this->render('chat/index.html.twig', [
            'form' => $form->createView(),
            'messages' => $messages,
        ]);
    }
}

templates/chat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat Communautaire{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .chat-container {
            max-width: 800px;
            margin: 0 auto;
            border: 1px solid #dee2e6;
            border-radius: 0.25rem;
            background-color: #f8f9fa;
            overflow: hidden;
        }
        .chat-messages {
            height: 500px;
            overflow-y: auto;
            padding: 20px;
            background-color: #e9ecef;
        }
        .chat-message {
            margin-bottom: 15px;
        }
        .chat-message .message-content {
            padding: 10px 15px;
            border-radius: 20px;
            display: inline-block;
            max-width: 70%;
        }
        .chat-message.left .message-content {
            background-color: #ffffff;
            border: 1px solid #dee2e6;
        }
        .chat-message.right .message-content {
            background-color: #0d6efd;
            color: #fff;
            border: 1px solid #0a58ca;
        }
        .chat-message .message-meta {
            font-size: 0.8rem;
            color: #6c757d;
            margin-top: 5px;
        }
        .chat-input {
            padding: 15px;
            background-color: #fff;
            border-top: 1px solid #dee2e6;
        }
    </style>
{% endblock %}

{% block body %}
<div class="container my-4">
    <h2 class="text-center mb-4">Chat Communautaire</h2>
    <div class="chat-container shadow">
        <div class="chat-messages" id="chat-messages">
            {% for message in messages %}
                <div class="chat-message {% if message.user.id == app.user.id %}right{% else %}left{% endif %}">
                    <div class="message-content">
                        {{ message.content }}
                    </div>
                    <div class="message-meta">
                        <strong>{{ message.user.username }}</strong> &middot; {{ message.createdAt|date('H:i') }}
                    </div>
                </div>
            {% else %}
                <p class="text-center text-muted">Aucun message pour le moment...</p>
            {% endfor %}
        </div>
        <div class="chat-input">
            {{ form_start(form) }}
            <div class="input-group">
                {{ form_widget(form.content) }}
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-paper-plane"></i>
                </button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var chatMessages = document.getElementById("chat-messages");
        chatMessages.scrollTop = chatMessages.scrollHeight;
    });
</script>
{% endblock %}